spring:
  application:
    name: data generation module
    currency_pairs:
      - EURUSD: 1.02 * resultTimeFunction + aLittleBitRandom
      - GBPUSD: 1.21 * resultTimeFunction + aLittleBitRandom
      - USDJPY: 135.02 * resultTimeFunction + aLittleBitRandom
      - USDCHF: 0.95 * resultTimeFunction + aLittleBitRandom
    const:
      - resultTimeFunction: "LocalTime.now().getSecond() % 2 == 0 ? 1.1 : 0.9"
      - aLittleBitRandom: "Math.random() - 0.5"

server:
  port: 8081

info:
  name: "data generation module"
  description: "Spring boot application for generation information on currency pairs"
  author: "Roman Orlov"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    build:
      enabled: true